In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [5]:
df_combined_all = pd.read_csv("df_combined_all.csv")

In [8]:
df_combined_all = df_combined_all.dropna()

In [9]:
df_combined_all

,subject,run,resp_000,resp_01B,resp_02B,resp_03B,resp_04B,difficulty,ppg_01B,ppg_02B,ppg_03B,ppg_04B
68,cp003,1,0.000,0.875,0.025,0.025,0.075,01B,1.000000,0.000000,0.000000,0.000000
69,cp003,2,0.025,0.625,0.050,0.075,0.225,01B,1.000000,0.000000,0.000000,0.000000
70,cp003,3,0.050,0.750,0.100,0.050,0.050,01B,1.000000,0.000000,0.000000,0.000000
80,cp008,1,0.000,0.475,0.250,0.175,0.100,01B,0.321053,0.157895,0.242105,0.278947
81,cp008,2,0.025,0.600,0.150,0.100,0.125,01B,0.273684,0.368421,0.121053,0.236842
...,...,...,...,...,...,...,...,...,...,...,...,...
482,cp042,2,0.625,0.275,0.075,0.025,0.000,04B,0.289474,0.357895,0.273684,0.078947
483,cp042,3,0.000,0.075,0.300,0.550,0.075,04B,0.178947,0.036842,0.157895,0.626316
484,cp043,1,0.000,0.200,0.300,0.475,0.025,04B,0.089474,0.121053,0.073684,0.715789
485,cp043,2,0.000,0.125,0.325,0.525,0.025,04B,0.189474,0.394737,0.205263,0.210526
486,cp043,3,0.000,0.250,0.175,0.550,0.025,04B,0.136842,0.136842,0.094737,0.631579

In [11]:
from pycaret.classification import *
pycaret_class = setup(data = df_combined_all, target = "difficulty", ignore_features=["resp_000", "subject", "run"], session_id=42)

In [12]:
best = compare_models()

Processing:   0%|          | 0/61 [00:00<?, ?it/s]